/* eslint-disable global-require */
module.exports = {
  askProjectName: require('./project-name'),
  askProjectFeatures: require('./project-features'),
  askProjectVersion: require('./project-version'),
  askProjectDescription: require('./project-description'),
  askPackageManager: require('./package-manager'),
  askProjectHomepage: require('./project-homepage'),
  askProjectDemoUrl: require('./project-demo-url'),
  askProjectDocumentationUrl: require('./project-documentation-url'),
  askAuhtorName: require('./author-name'),
  askAuthorGithub: require('./author-github'),
  askAuthorEmail:require('./author-email'),
  askAuthorWebsite: require('./author-website'),
  askAuthorTwitter: require('./author-twitter'),
  askAuthorLinkedIn: require('./author-linkedin'),
  askAuthorPatreon: require('./author-patreon'),
  askProjectPrerequisites: require('./project-prerequisites'),
  askLicenseName: require('./license-name'),
  askLicenseUrl: require('./license-url'),
  askIssuesUrl: require('./issues-url'),
  askContributingUrl: require('./contributing-url'),
  askInstallCommand: require('./install-command'),
  askUsage: require('./usage'),
  askTestCommand: require('./test-command')
}
